In [1]:
import numpy as np

In [2]:
a = np.array([
              [1, 2, 3],
              [4, 5 , 6]
])
print('a =\n', a)
b = np.array([
              [2, 4, 6],
              [3, 5, 7]
])
print('b =\n', b)

a =
 [[1 2 3]
 [4 5 6]]
b =
 [[2 4 6]
 [3 5 7]]


In [15]:
c = a+b
d = a-b
e = a*b
print('a+b =\n ', c)
print('a-b =\n', d)
print('a*b =\n', e)

a+b =
  [[ 3  6  9]
 [ 7 10 13]]
a-b =
 [[-1 -2 -3]
 [ 1  0 -1]]
a*b =
 [[ 2  8 18]
 [12 25 42]]


In [8]:
def chuyen_vi(mt):
  f = print(mt.transpose())
  return f

In [10]:
chuyen_vi(a)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
chuyen_vi(b)

[[2 3]
 [4 5]
 [6 7]]
